app = "dccassistant-bot"
primary_region = "syd"

[build]

[env]
PORT = "8080"

[[services]]
protocol = "tcp"
internal_port = 8080
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

  [[services.ports]]
  port = 80

  [[services.ports]]
  port = 443

[processes]
app = "gunicorn -b 0.0.0.0:8080 bot:app"
